# Gate-level power simulation for the Quartus Power Analyzer (ModelSim-Intel FPGA Starter).
#
# 1. Quartus: Settings > EDA Tool Settings > Simulation: ModelSim-Altera, Verilog HDL,
#    tick "Generate Value Change Dump (VCD) file script", design instance name = de10_top_tb/dut.
#    Processing > Start > Start EDA Netlist Writer.
# 2. ModelSim: File > Change Directory -> scaffold/syn/simulation/modelsim, then in the Transcript:
#        do ../../../tb/power/power.do shake        (or: idle)
#    It skips the 12 ms boot, records 100 ms of activity (40 samples) into <case>.vcd, and quits.
#    Gate-level simulation is slow: expect several minutes to tens of minutes.
# 3. Quartus: Processing > Power Analyzer Tool > Add Power Input File(s) > <case>.vcd,
#    entity de10_top_tb/dut, then Start. Confidence should no longer be "Low".

if {$argc >= 1} { set case $1 } else { set case shake }
quietly set tb ../../../tb

vlib work
vlog de10.vo
vlog -sv $tb/adxl345_model.sv $tb/power/power_tb.sv
vsim -t 1ps -L fiftyfivenm_ver -L altera_ver -L altera_mf_ver -L lpm_ver \
     -G SAMPLE_FILE=$tb/power/$case.hex work.de10_top_tb

run 12ms                                   ;# reset + sensor boot (10 ms) + loader: not part of the measurement
source de10_dump_all_vcd_nodes.tcl         ;# generated by Quartus: starts recording every node into de10.vcd
run 100ms                                  ;# 40 samples at 2.5 ms
vcd flush
quit -sim
file rename -force de10.vcd $case.vcd
echo "wrote $case.vcd"
