// [SCAFFOLD: written by Claude, not part of the main design]
import snn_pkg::*;

// Loads the trained network into the snn memories after reset.
// The ROM is filled at compile time from ROM_FILE ($readmemh, generated by snn/train_live.py --rom),
// so the weights are part of the bitstream and no host connection is needed.
//
// ROM format (64-bit words):
//   word 0 : {n_cmd[15:0], 48'b0}                     number of write commands that follow
//   word k : {type[1:0], addr[13:0], payload[47:0]}    one memory write
//     type 0  config_mem  : payload {threshold[47:32], decay[31:28], reset[27:12], num_layers[11:0]}
//     type 1  layer meta  : payload {start[14:8], count[7:0]}
//     type 2  neuron meta : payload {start[24:13], count[12:0]}
//     type 3  connection  : payload {src[29:23], dst[22:16], weight[15:0]}
module snn_loader #(
    parameter      ROM_FILE  = "snn_rom.hex",   // path relative to the Quartus project / simulator
    parameter int  ROM_DEPTH = 4096
) (
    input  logic        clk,
    input  logic        reset,

    output logic        loaded,                 // HIGH once every command has been written

    // write command for the snn ports (address and payload fields of the current ROM word)
    output logic [63:0] cmd,
    output logic        config_wen,
    output logic        layer_meta_wen,
    output logic        neuron_meta_wen,
    output logic        conn_wen
);

logic [63:0] rom [0:ROM_DEPTH-1];
logic [63:0] rom_q;
logic [$clog2(ROM_DEPTH)-1:0] rom_addr;

initial $readmemh(ROM_FILE, rom);
always_ff @(posedge clk) rom_q <= rom[rom_addr];       // 1-cycle read latency (M9K)

typedef enum logic [2:0] { HDR, HDR_W, RD, WR, DONE } state_t;
state_t state;

logic [15:0] n_cmd, k;

always_ff @(posedge clk) begin
    if (reset) begin
        state           <= HDR;
        rom_addr        <= '0;
        loaded          <= 1'b0;
        config_wen      <= 1'b0;
        layer_meta_wen  <= 1'b0;
        neuron_meta_wen <= 1'b0;
        conn_wen        <= 1'b0;
        cmd             <= '0;
        n_cmd           <= '0;
        k               <= '0;
    end else begin
        config_wen      <= 1'b0;                        // write enables are 1-cycle pulses
        layer_meta_wen  <= 1'b0;
        neuron_meta_wen <= 1'b0;
        conn_wen        <= 1'b0;

        case (state)
            HDR:   state <= HDR_W;                      // rom_addr = 0, wait for the read
            HDR_W: begin
                n_cmd    <= rom_q[63:48];
                k        <= 16'd1;
                rom_addr <= 1;
                state    <= (rom_q[63:48] == 0) ? DONE : RD;
            end
            RD:    state <= WR;                         // wait for the read
            WR: begin
                cmd <= rom_q;
                case (rom_q[63:62])
                    2'd0: config_wen      <= 1'b1;
                    2'd1: layer_meta_wen  <= 1'b1;
                    2'd2: neuron_meta_wen <= 1'b1;
                    2'd3: conn_wen        <= 1'b1;
                endcase
                if (k == n_cmd) state <= DONE;
                else begin
                    k        <= k + 1'b1;
                    rom_addr <= rom_addr + 1'b1;
                    state    <= RD;
                end
            end
            DONE:  loaded <= 1'b1;
            default: state <= HDR;
        endcase
    end
end

endmodule
